#!/bin/bash

# set this to workaround expr problems in shFlags on freebsd
if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
  set -x
fi

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export BPMN_SCM_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
export GIT_DIR=.bpmn
export GIT_WORK_TREE=.

usage() {
    echo "usage: bpmn <command> [<args>]"
    echo
    echo "These are common BPMN comands used in various sitations:"
    echo
    echo "Start a working area"
    echo "    init      Crate an empty BPMN repository"
    echo
    echo "work on the current change (see also: bpmn help everyday)"
    echo "    add       Add file contents to the index"
    echo "    reset     Reset current HEAD"
    echo "    rm        Remove files from the working tree and from index"
    echo
    echo "examine the history and state (see also: bpmn help revisions)"
    echo "    log       Show commit logs"
    echo "    status    Show the working tree status"
}

main() {
    # When there are no options
    if [ $# -lt 1 ]; then
        usage
        exit 1
    fi

    . "$BPMN_SCM_DIR/bpmn-common"

    export POSIXLY_CORRECT=1

    . "$BPMN_SCM_DIR/bpmn-shFlags"
    FLAGS_PARENT="bpmn"

    # allow user to request git action logging
    DEFINE_boolean show_commands false 'show actions taken (git commands)' g

    # do actual parsing
    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    # sanity checks
    SUBCOMMAND="$1"; shift;
    if [ -e "$BPMN_SCM_DIR/bpmn-$SUBCOMMAND" ]; then
        # run command
        . "$BPMN_SCM_DIR/bpmn-$SUBCOMMAND"
        FLAGS_PARENT="bpmn $SUBCOMMAND"

        # run the specified action
        if [ "$1" == "help" ]; then
            cmd_help
        else
            cmd_exec "$@"
        fi
    else
        usage
        exit 1
    fi
}

main "$@"
